image: node:lts-alpine
before_script:
    - cp src/config.ts.sample src/config.ts
    - cp src/styles.ts.sample src/styles.ts
    - apk update
    - apk add git
    - npm i

stages:
    - build
    - publish

# Run pipelines on MR, tags and push on 'main'
workflow:
    rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        - if: ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web") && $CI_COMMIT_TAG
        - if: ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web") && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

lint:
    stage: build
    script:
        - npm run lint

test:
    stage: build
    script:
        - npm run test

build:
    stage: build
    script:
        - npm run build

pages:
    stage: publish
    rules:
        - if: ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web") && $CI_COMMIT_TAG
          variables:
              ENVIRONMENT_NAME: $CI_COMMIT_TAG
        - if: ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web") && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          variables:
              ENVIRONMENT_NAME: $CI_COMMIT_BRANCH
    variables:
        DEPLOY_URL: https://piero.giro3d.org
        OUTPUT: ./dist
    cache:
        key: gitlab-pages
        paths:
            - node_modules
    environment:
        name: pages/$ENVIRONMENT_NAME
        action: start
        url: $DEPLOY_URL
    artifacts:
        paths:
            - dist
        name: $ENVIRONMENT_NAME
    publish: dist
    script:
        - npm run build -- --out-dir $OUTPUT --base $DEPLOY_URL
