pages:
    stage: build
    image: node:lts-alpine
    script:
        - npm i
        - npm run lint
        # for some reason, optimization removes useful stuff...
        # see https://github.com/parcel-bundler/parcel/issues/7622
        - npm run build -- --no-optimize
        - mv dist public
    artifacts:
        paths:
            - public
        name: "$CI_COMMIT_REF_SLUG"
    only:
        - main
